### ISSUE TITLE
Exception in CalabashRunner : calabash.java.CalabashException

### ISSUE THREAD

**Issue by avikashgorka** [navaneeth/calabash-ios-java#11]
Hi,

I am getting exception while running below statement. 

CalabashRunner runner = new CalabashRunner(new File("/Users/User1/Desktop/TestCalabash//TestCalabash.xcodeproj").getAbsolutePath());

Below is the exception : 
calabash.java.CalabashException: '/Users/User1/Desktop/TestCalabash/TestCalabash.xcodeproj' is not a valid project path. Can't find .xcodeproj directory
    at calabash.java.CalabashRunner.<init>(CalabashRunner.java:67)
    at calabash.java.CalabashRunner.<init>(CalabashRunner.java:36)

Please help.

Regards,
Avikash

**Comment by vishnukarthikl** [comment]
Hi Avikash,

Can you point the CalabashRunner to `/Users/User1/Desktop/TestCalabash` instead of pointing it to the .xcodeproj

``` java
CalabashRunner runner = new CalabashRunner(new File("/Users/User1/Desktop/TestCalabash").getAbsolutePath());
```

Thanks
Vishnu

**Comment by avikashgorka** [comment]
Thanks Vishnu, it worked.

But now I am getting below exception:

calabash.java.CalabashException: Failed to start iOS application. (RuntimeError) Error... Unable to find APP_BUNDLE_PATH.
Cannot find a built app that is linked with calabash.framework
Please build your app from Xcode
You should build your calabash target.

Alternatively, specify APP_BUNDLE_PATH in features/support/01_launch.rb
This should point to the location of your built app linked with calabash.

```
at calabash.java.CalabashWrapper.start(CalabashWrapper.java:91)
at calabash.java.CalabashRunner.start(CalabashRunner.java:307)
```

**Comment by vishnukarthikl** [comment]
You will have to first build the calabash target from your xcode before calling runner.start().
runner.setup() will create the <project>-cal target, but you have to build it through xcode.
for eg:
![setup](http://www.thoughtworks.com/products/docs/twist/13.3/help/resources/images/calabash_ios_xcode_target_build1.png)
![build](http://www.thoughtworks.com/products/docs/twist/13.3/help/resources/images/calabash_ios_xcode_target_build2.png)
After you have 
I just realized that this hasn't been mentioned in the getting started guide. Will update it.

**Comment by avikashgorka** [comment]
Vishnu,

I did that, but still finding the same issue..I am not sure where am I doing wrong. I am new to IOS environment.

**Comment by avikashgorka** [comment]
Vishnu, 

May I ask you to send me 1:1 steps written from the beginning to last. That will be great help.

You can send me on my mailer :  avikash20mca2k5@yahoo.com

Regards,
Avikash

**Comment by navaneeth** [comment]
Check where your build files are written by Xcode. You need assign that path into APP_BUNDLE_PATH environment variable.

**Comment by avikashgorka** [comment]
Hi 

That issue is resolved.

But now I am facing below issue : 

calabash.java.CalabashException: Failed to start iOS application. (RuntimeError) Unable to find AutomationInstrument.bundle
    at calabash.java.CalabashWrapper.start(CalabashWrapper.java:91)
    at calabash.java.CalabashRunner.start(CalabashRunner.java:307)
    at cucumber.TestCalabash_WithMain.main(TestCalabash_WithMain.java:15)

**Comment by ChathuraP** [comment]
I have face the same above Issue:
Generate Error while execute calabash.java.CalabashWrapper.start() method
 "org.jruby.embed.EvalFailedException: (RuntimeError) Unable to find AutomationInstrument.bundle"
